apiVersion: v1
kind: Service
metadata:
  name: dns-svc
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
