apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: old-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: old-app
      labels:
        app: old-app
    spec:
      containers:
      - name: nginx
        image: goodist/otus-nginx:6
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
        volumeMounts:
        - name: app
          mountPath: /app
      initContainers:
      - name: busybox
        image: busybox:1.31
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        emptyDir: {}
