apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-read-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-cluster-only
subjects:
- kind: Group
  name: system:serviceaccounts
  namespace: prometheus
