apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-user
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: base-user
subjects:
- kind: ServiceAccount
  name: dave
  namespace: dev
