apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:0.10.0"
          args: ["-nginx.scrape-uri", "http://nginx/basic_status"]
          ports:
            - containerPort: 9113
              name: http
