apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
spec:
  ingressClassName: nginx
  rules:
  - host: shop.158.160.74.40.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
